parsers:
- code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const { 'Rule': rules = [], 'Proxy Group':groups = [] } = rawObj
        return yaml.stringify({ ...rawObj, 'proxy-groups': groups, rules })
      }
  reg: .*$
  yaml:
    commands:
    - proxy-groups.节点选择.proxies=[]proxyNames
    - proxy-groups.节点选择.proxies.0+全球直连
    - proxy-groups.节点选择.proxies.1+自动选择
    - proxy-groups.自动选择.proxies=[]proxyNames
    - proxy-groups.哔哩哔哩.proxies=[]proxyNames
    - proxy-groups.哔哩哔哩.proxies.0+全球直连
    - proxy-groups.哔哩哔哩.proxies.1+节点选择
    - proxy-groups.STEAM.proxies=[]proxyNames
    - proxy-groups.STEAM.proxies.0+全球直连
    - proxy-groups.STEAM.proxies.1+节点选择
    mix-rule-providers:
      Bilibili:
        behavior: classical
        path: ./Rules/Bilibili.yaml
        type: file
      BanAD:
        behavior: classical
        path: ./Rules/BanAD.yaml
        type: file
      BanEasyList:
        behavior: classical
        path: ./Rules/BanEasyList.yaml
        type: file
      BanEasyListChina:
        behavior: classical
        path: ./Rules/BanEasyListChina.yaml
        type: file
      BanEasyPrivacy:
        behavior: classical
        path: ./Rules/BanEasyPrivacy.yaml
        type: file
      BanProgramAD:
        behavior: classical
        path: ./Rules/BanProgramAD.yaml
        type: file
      BilibiliHMT:
        behavior: classical
        path: ./Rules/BilibiliHMT.yaml
        type: file
      ChinaCompanyIp:
        behavior: classical
        path: ./Rules/ChinaCompanyIp.yaml
        type: file
      ChinaDomain:
        behavior: classical
        path: ./Rules/ChinaDomain.yaml
        type: file
      Download:
        behavior: classical
        path: ./Rules/Download.yaml
        type: file
      GoogleCN:
        behavior: classical
        path: ./Rules/GoogleCN.yaml
        type: file
      GoogleFCM:
        behavior: classical
        path: ./Rules/GoogleFCM.yaml
        type: file
      LocalAreaNetwork:
        behavior: classical
        path: ./Rules/LocalAreaNetwork.yaml
        type: file
      Microsoft:
        behavior: classical
        path: ./Rules/Microsoft.yaml
        type: file
      OneDrive:
        behavior: classical
        path: ./Rules/OneDrive.yaml
        type: file
      ProxyGFWlist:
        behavior: classical
        path: ./Rules/ProxyGFWlist.yaml
        type: file
      ProxyLite:
        behavior: classical
        path: ./Rules/ProxyLite.yaml
        type: file
      ProxyMedia:
        behavior: classical
        path: ./Rules/ProxyMedia.yaml
        type: file
      Steam:
        behavior: classical
        path: ./Rules/Steam.yaml
        type: file
      Telegram:
        behavior: classical
        path: ./Rules/Telegram.yaml
        type: file
      UnBan:
        behavior: classical
        path: ./Rules/UnBan.yaml
        type: file
      Apple:
        behavior: classical
        path: ./Rules/Apple.yaml
        type: file
      mydirect:
        behavior: classical
        path: ./Rules/mydirect.yaml
        type: file
    prepend-proxy-groups:
    - name: 节点选择
      type: select
    - name: 其余
      proxies:
      - 节点选择
      - 全球直连
      type: select
    - name: OneDrive
      proxies:
      - 全球直连
      - 节点选择
      type: select
    - name: 微软服务
      proxies:
      - 全球直连
      - 节点选择
      type: select
    - name: 哔哩哔哩
      type: select
    - name: STEAM
      type: select
    - interval: 300
      name: 自动选择
      tolerance: 50
      type: url-test
      url: http://www.gstatic.com/generate_204
    - name: 全球直连
      proxies:
      - DIRECT
      - REJECT
      type: select
    - name: 全球拦截
      proxies:
      - REJECT
      - DIRECT
      type: select
    prepend-rules:
    - RULE-SET,LocalAreaNetwork,DIRECT
    - RULE-SET,mydirect,全球直连
    - DOMAIN-SUFFIX,azureedge.net,节点选择
    - RULE-SET,UnBan,全球直连
    - RULE-SET,BanAD,全球拦截
    - RULE-SET,BanProgramAD,全球拦截
    - RULE-SET,BanEasyList,全球拦截
    - RULE-SET,BanEasyListChina,全球拦截
    - RULE-SET,BanEasyPrivacy,全球拦截
    - RULE-SET,GoogleCN,全球直连
    - RULE-SET,GoogleFCM,节点选择
    - RULE-SET,OneDrive,OneDrive
    - RULE-SET,Microsoft,微软服务
    - RULE-SET,Apple,全球直连
    - RULE-SET,Telegram,节点选择
    - RULE-SET,Steam,STEAM
    - RULE-SET,Bilibili,哔哩哔哩
    - RULE-SET,BilibiliHMT,哔哩哔哩
    - RULE-SET,ProxyMedia,节点选择
    - RULE-SET,ProxyLite,节点选择
    - RULE-SET,ProxyGFWlist,节点选择
    - RULE-SET,ChinaDomain,全球直连
    - RULE-SET,ChinaCompanyIp,全球直连
    - RULE-SET,Download,全球直连
    - GEOIP,CN,全球直连
    - MATCH,其余
